version: '3'

services:
  app:
    build: './src/app'
    volumes:
      - './src/app:/usr/local/apache2/htdocs/'
    ports:
      - '80:80'

  github-release:
    image: 'github-release'
    build: './src'
